# Hydrogen

spacing         = 2
padding         = 0

hide_ascii      = true
prefer_small_ascii = true

separator       = "="
key_color       = "Cyan"
separator_color = "Cyan"

[palette]
type = "Full"
visible = true

[bar]
glyph           = "/"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = false

[box]
border          = "rounded"
visible         = false

[box.inner_margin]
x               = 2
y               = 1

[randomize]
key_color       = false
separator_color = false

[keys]
# host            ="Host"
kernel          = "Kernel"
battery         = "Power"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Pkgs"
uptime          = "Uptime"
memory          = "RAM"
machine         = "Box"
local_ip        = "Local IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU"
cpu             = "Chip"
gpu             = "GPU"
disk_space      = "Disk Space"
