theme = 'mikedecr'

long_uptime = false
long_shell = false
physical_cores = true

show = [
  "Host",
  "Machine",
  "OperatingSystem",
  "Packages",
  "Shell",
  "Uptime",
  "Processor",
  "ProcessorLoad",
  "Memory",
  "Battery",
]
# hidden values: "Kernel", "Distribution", "DesktopEnvironment", "WindowManager",
#                "Resolution", "Backlight", "LocalIP", "Terminal", "GPU", "DiskSpace"
